name: CI
on:
  push:
    branches: [ "Vip" ]
  pull_request:
    branches: [ "Vip" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tự động hóa
        run: |
          ls
          env
          java -version
